### ISSUE TITLE
I could not find what I was looking for - this.state.refine locks up page...

### ISSUE THREAD

**Issue by mswilson4040** [algolia/instantsearch.js#2579]
I am using algolia in my Angular 5 application and everything is working perfectly. I chose to work with the connectors rather than using the out of the box components.

However, what I find very strange is that when I'm working with the refinersListConnector or the searchBoxConnector, the function to be called to apply the search/refiner isn't asynchronous.

Following the documentation: https://community.algolia.com/instantsearch.js/v2/guides/angular-integration.html

For example:

In the documentation, you have a piece of code that updates the query:

```
handleChange(query) {
  this.state.refine(query);
}
```

Then you state: 

> ..We will use Angular data binding to update the query and call this.state.refine() function every time the input value changes:

Now, the result I get is exactly what I am expecting. However, the user experience is less than favorable because the page locks up after a user enters a single key. I have set a min char count of 3 so that the results can be narrowed down more and thus lowering the page lock-up time, but it still isn't good. It's quite annoying to have this issue for the refiners and especially the search box.

Is there any future plans or current functionality that would get me around this page lockup issue? I was hoping that `this.state.refine` would return a promise or something, but it doesn't.

**Comment by Haroenv** [comment]
Could you make a repository that shows this behaviour? it’ll be very helpful in debugging!

**Comment by mswilson4040** [comment]
It's following the documentation step by step. If you follow the documentation in the Angular2 + Instasearch, you'll be able to see the issue.

**Comment by mswilson4040** [comment]
It's even staying in the documentation that the state.refine function returns undefined. There should be an option for `state.refine.then( result => { //do something with result }, error => { // handle error });`

querystring
The query from the last search.

onHistoryChange(SearchParameters) => undefined
Registers a callback when the browser history changes.

refine(string) => undefined
Sets a new query and searches.

clear() => undefined
Remove the query and perform search.

widgetParamsObject
All original CustomSearchBoxWidgetOptions forwarded to the renderFn.

**Comment by bobylito** [comment]
Hello @mswilson4040 

The refine function that is provided doesn't return a promise by design. It is however non blocking and it shouldn't block the input. This is the same methods that are used to implement all the widgets  in InstantSearch.js. For example using [in the e-commerce demo, the input is not blocked](https://community.algolia.com/instantsearch.js/v2/examples/e-commerce/).

If you want to listen to listen to the results update, you need to go a level deeper and use the helper. You can use it directly from InstantSearch by [making a custom widget](https://community.algolia.com/instantsearch.js/v2/guides/custom-widget.html) or by [using it alone](https://community.algolia.com/algoliasearch-helper-js/).

**Comment by mswilson4040** [comment]
@bobylito Thanks for providing the information. If the function is non-blocking than I will have to look at what else is blocking it. I will also try the helper to see if that gives me what I want.

**Comment by mswilson4040** [comment]
I think I see the difference. The E-Commerce demo is using the out of the box agolia component:

```
<input type="text" class="form-control" id="q" />

search.addWidget(
  instantsearch.widgets.searchBox({
    container: '#q',
    placeholder: 'Search a product'
  })
);
```

In the case of using the searchBoxConnector, the page locks up whenever you search or select a refiner. This can be reproduced using the code in your documentation:

```
import { Component, OnInit } from '@angular/core';
import { connectSearchBox } from 'instantsearch.js/es/connectors';

import { InstantSearchService } from '../../services/instantsearch.service';

@Component({
  selector: 'app-search-box',
  template: `<p>It works</p>`,
  styles: []
})
export class SearchBoxComponent implements OnInit {
  // Define SearchBox initial state
  state: { query: string; refine: Function } = {
    query: '',
    refine() {}
  };

  constructor(private instantSearchService: InstantSearchService) {}

  ngOnInit() {
    const widget = connectSearchBox(this.updateState);
    this.instantSearchService.search.addWidget(widget());
  }

  updateState = (state, isFirstRendering) => {
    // asynchronous update of the state
    // avoid `ExpressionChangedAfterItHasBeenCheckedError`
    if (isFirstRendering) {
      return Promise.resolve(null).then(() => {
        this.state = state;
      });
    }

    this.state = state;
  }
}
```
```
template: `
  <input
    type="text"
    [value]="state.query"
    (input)="handleChange($event.target.value)"
  />
`
```
handleChange(query) {
  this.state.refine(query) //page locks up every key press
}

**Comment by iam4x** [comment]
Hello @mswilson4040 we have released a beta of angular-instantsearch that you can find here: https://github.com/algolia/angular-instantsearch

Can you please try it and give us feedback for this library? We will deprecate and remove this guide at some point.

Cheers, Maxime.

**Comment by mswilson4040** [comment]
@iam4x I will definitely check it out, but would like to figure out how to resolve this issue still. It looks like the angular-instantsearch is basically the same as using the out of the box algolia components, but more angularized. My use case requires me to be able to have much more control over how things are styles, and how they function so using the connectors makes the most sense for this project.

I did pull down the angular-instantsearch and ran into issues when I tried to use it (missing provider issues). I'll open GitHub issues for those.

**Comment by iam4x** [comment]
Hi @mswilson4040 

I have implemented used the guide into an Angular5 application, I cannot reproduce your issue. Could you create a repository so I can debug it?

And yes thank you, it would be nice if you could create those issues 👍

**Comment by mswilson4040** [comment]
I figured out why it was happening. I am using the angular material Expansion Panel for my hits. I'm guessing that the expansion panel is quite expensive to render so as you're typing away in the instant search text box, the page locks up since it's trying to repaint the dom.

I commented out my expansion panel for the hits and just changed it to a simple div. The page no longer locks up and everything works as expected.

**Comment by bobylito** [comment]
> I commented out my expansion panel for the hits and just changed it to a simple div. The page no longer locks up and everything works as expected.

Oh good you figured out what was expensive to render 👍. Do you think there is something to improve on our end concerning this issue?

**Comment by mswilson4040** [comment]
There may be some kind of guidance as to the recommended setup for hits, I guess. Obviously rendering some elements are going to take longer than others (such as this case). Given that Angular Material is still in the early stages, there's probably nothing that can be done until things get more finalized on the angular side. Thanks

**Comment by bobylito** [comment]
Ok thanks @mswilson4040 for your patience and your feedbacks.

I am closing this issue for now then.
